### ISSUE TITLE
Expose a method to check if the session is valid

### ISSUE THREAD

**Issue by dabitdev** [atmcoin/cash-sdk-ios#6]
This is an example of the method with the test server
```
https://secure.just.cash/atm/auth/user?sessionKey=xxx 
```

**Comment by gianpac** [comment]
Error 105 on any API call
{"result":"error","error":{"code":"105","server_message":"Session timeout"},"data":null}

**Comment by dabitdev** [comment]
would you like to put a method to our protocol?

```
 isSessionValid(): Boolean
```

**Comment by gianpac** [comment]
we can also do that, sure

**Comment by gianpac** [comment]
On failure of sessionKey (error code 105), session will renew and retry the call that failed. Also implemented isSessionValid (currently not used)
https://github.com/atmcoin/cash-sdk-ios/commit/3047925a6856819add93097e25265d32cf5997ae
